# Generated by Django 3.0.4 on 2020-03-13 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('crawl_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
