# Generated by Django 2.1.15 on 2020-03-13 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawling_tweets', '0005_auto_20200314_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
    ]
