# Generated by Django 2.1.15 on 2020-03-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0006_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
