# Generated by Django 2.1.15 on 2020-03-13 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0013_auto_20200314_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='crawl_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='crawl_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
