# Generated by Django 2.1.15 on 2020-03-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0016_auto_20200314_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='crawl_date',
            field=models.DateTimeField(verbose_name=['%Y-%m-%d %H:%M:%S']),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
