# Generated by Django 2.1.15 on 2020-03-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0019_auto_20200314_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='link_detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='link_detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(),
        ),
    ]
