# Generated by Django 2.1.15 on 2020-03-16 11:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawling_tweets', '0021_auto_20200316_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.BigIntegerField()),
                ('comment_content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('link_detail', models.TextField()),
                ('number_of_reply', models.FloatField()),
                ('number_of_react', models.FloatField()),
                ('crawl_date', models.DateTimeField(verbose_name=['%Y-%m-%d %H:%M:%S'])),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuidPost', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_id', models.BigIntegerField()),
                ('post_content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('link_detail', models.TextField()),
                ('number_of_reply', models.FloatField()),
                ('number_of_retweet', models.FloatField()),
                ('number_of_react', models.FloatField()),
                ('crawl_date', models.DateTimeField(verbose_name=['%Y-%m-%d %H:%M:%S'])),
                ('keyword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='uuidPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling_tweets.Post'),
        ),
    ]
