# Generated by Django 2.1.15 on 2020-03-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0023_auto_20200316_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uuidComment',
            new_name='uuid_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='uuidPost',
            new_name='uuid_post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='uuidPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling_tweets.Post', to_field='uuidPost'),
        ),
    ]
