# Generated by Django 2.1.15 on 2020-03-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0024_auto_20200316_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword_Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Keyword_Crawler',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='uuidPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling_tweets.Post'),
        ),
    ]
