# Generated by Django 2.1.15 on 2020-03-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0025_auto_20200316_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword_Crawler',
        ),
    ]
