# Generated by Django 2.1.15 on 2020-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0026_delete_keyword_crawler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword_Crawler',
            fields=[
                ('keyword', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Keyword_Crawler',
            },
        ),
    ]
