# Generated by Django 2.1.15 on 2020-03-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0027_keyword_crawler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uuidPost',
            new_name='uuid_post',
        ),
    ]
