# Generated by Django 2.1.15 on 2020-03-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0028_auto_20200325_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('available', models.BooleanField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'Keyword',
            },
        ),
    ]
