# Generated by Django 2.1.15 on 2020-03-25 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0029_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uuid_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawling_tweets.Post'),
        ),
    ]
