# Generated by Django 2.1.15 on 2020-03-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0030_auto_20200325_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uuid_post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
