# Generated by Django 2.1.15 on 2020-04-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_tweets', '0032_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
    ]
